dist: trusty
sudo: false
language: node_js
node_js:
  - "6"
os:
  - linux
cache: yarn
before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install latest chrome.
  - export CHROME_BIN=chromium-browser
  # Use newer Yarn version
  - npm install -g yarn@0.27.5
install:
  - yarn install
script:
  - npm run build
  - npm run testCIChrome