language: nix
# see https://docs.travis-ci.com/user/languages/nix
# and https://nixos.wiki/wiki/Nix_on_Travis
sudo: false
services:
- docker
before_install:
- sudo mkdir -p /etc/nix
# make sure no browser is left over that can disturb the karma tests (nix-shell provides the browsers!)
- sudo apt-get remove google-chrome-stable -y
- sudo apt-get remove chromium-browser -y
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

env:
  global:
    - # Environment variables for Docker
    - secure: "N7HtB4n0MMi41zqhLPl3SK+C2e7hIxiWosYictCGLfY4Ncxda4zhzXYDqwrc9id1o0Uj78TkU8CQgUGMm8a52x5yTIzmRyEZnH9F/YOREGomW/akV/A8iw4RssFW85zUgGlPT7EsHkBeEkavSbxSa7gxvOaeDY9UsWI0I3Bks2AQmiZE3+sWAt524/SW2Z79tqtQXKvFcQ857lkaQ7yILU8q/Ua7hAORyzSrjZGpcQmdAw7xJwBrZchlFfpPfkJkGwBfqK3nyEgT6bcBUXeSTk5R3hCw0x43cjrJbrhyDNb4Uhla9qFw+eCoBoHd1rT+Zj6v7hykbqUMVd1qutZFiXUTy42R0oCgM5+3iC/zNWrBBDRPZ6CuqJ3G7q4ixm9A1Ny6RypPEhISOlPQdWLp8sXm3hqt7Tukis9SobllXdeg+Nq4f2kk07O+scycbY0x8Xg6YaOENbBXzNHTFzF2WHxolVm4UnVDMEahGUcIDYQiMX+96IyyH6/K8hN2ME0pMKlEOEU8QJY2eNLXNPG43sjZ40XdfNYbBI2kb+1cUZ8xWDsu6GAq4OClphvoT0A1CwXb0cfoxWm1sf4zQS5pcMPfBfagpD7viJJL+7HsNssnvzK8naMNZbtRECdY34Mf9MfrciKBBx8I1kZB1dMFmltQSRQVJeuo2wr2j2Jeyps="
    - secure: "pM16+kFAEv0CYmmTAK1xR9fTOuLpxWirW0cfcbTqv2W6LQEKSxNennXQOfvt3U4Qt1v+Us/vCjT+5UYRhR0F/iW0d0U9kGWVKHd/WF0NA8li4WLRMfuMvmzdtwMNv5y1lw+/rCEDviGQV31JPF+8toy2UA9FAu33R/t8NrUahkulplYV+yTCgKZqUlxp1mFxDg+9UcXKqx5XitYVb6le0PYvmoG9Mtncq1uOlnaremepVmdxyXWadakjmHzLQ/0OViZp/BW7F2qbUhVsvePRSiI48A+Veb0J0pwAW7KmFy7zFnWZq1Uy0a4T+uFh2U9Ja1LQCfwWdnbZixyQT6DFlvCcAh5fukKQe5Wc7rdtGQ1EVUK9Fhs6Is88sKvg+cxZHYOf4h7hfIVrKXNM/5cjTm35qUbWVxqYiAdvmXSrfDh0our5QwuoDbW2IxcAVFWO6+JEe7Kr3wPDPOESJQOq/tr3kyoNv5PrdBtckyIXnZR7I7JIuHCV+kBX9j5Qt03YdWMULoBUh9k+I8VnrMbVuLltRFRXnMdmtBPMBrPmdEW87bAuWu6sCX60UvLQTOGIn4pA/CDnzKiTizaJcA0EtKfLn4SVfyiJlsSh48+8GIwr04n1n084oz0CDPRLXEiBwMbQnJLn9NNfhJTk12RxhYuYVj6FKp9T32elUyxtD6Q="
    - NIXPKGS_ALLOW_UNFREE: 1

  matrix:
    - FIREFOX_VERSION="latest"
    - FIREFOX_VERSION="60-esr"

install:
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn install"
script:
- nix-shell shell-${FIREFOX_VERSION}.nix --command "firefox --version"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "google-chrome --version"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn run build" # includes lint
- nix-shell shell-${FIREFOX_VERSION}.nix --command "xvfb-run --server-args=\"-ac -screen 0 1920x1080x16\" yarn run testCIFirefox"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "xvfb-run --server-args=\"-ac -screen 0 1920x1080x16\" yarn run e2e" # currently non functional
- if [[ ( "$TRAVIS_PULL_REQUEST" = "false" ) && ( "$FIREFOX_VERSION" = "latest" ) && (( "$TRAVIS_BRANCH" = "master" ) || ( "$TRAVIS_TAG" != "" )) ]]; then nix-shell shell-${FIREFOX_VERSION}.nix --command  "yarn run docker:build" && export TE_DEPLOY=true; fi

deploy:
  provider: script
  script: bash docker_push
  on:
    condition: "$TE_DEPLOY != ''"
    all_branches: true
