dist: trusty
sudo: false
language: node_js
node_js:
  - "6"
os:
  - linux
cache: yarn
before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install latest chrome.
  - export CHROME_BIN=chromium-browser
  # Use newer Yarn version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - npm run build
  - npm run testCIChrome
