sudo: false
dist: trusty

cache: yarn

env: 
  - FIREFOX_VERSION="latest"
  - FIREFOX_VERSION="58.0.2"

language: node_js
node_js:
  - "6"
os:
  - linux
before_install:
  # Install firefox for testing.
  - echo $FIREFOX_VERSION
  - export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-'$FIREFOX_VERSION'&lang=en-US&os=linux64'
  - wget --no-verbose -O /tmp/firefox-$FIREFOX_VERSION.tar.bz2 $FIREFOX_SOURCE_URL
  - mkdir /tmp/firefox-$FIREFOX_VERSION
  - tar -xvf /tmp/firefox-$FIREFOX_VERSION.tar.bz2 -C /tmp/firefox-$FIREFOX_VERSION
  - export PATH=/tmp/firefox-$FIREFOX_VERSION/firefox:$PATH 
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install latest chrome.
  - export CHROME_BIN=chromium-browser
  # Use newer Yarn version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script: 
  - npm run build
  - firefox --version
  - npm run testCIFirefox
deploy:
  skip_cleanup: true
  provider: npm
  email: service.eng@akquinet.de
  api_key:
    secure: Qjyy7EQa3DbWiOMM8xVA5ZAa7smoHbSZjIuOOJG2f+JLQFAUqFIhgOY4Hw4bmI6l1r8OTW3jWDmsB1VcqCud6lmPsSBuTbWJrG5zvXALyKwD58qTjgkih6FodDAkG6+0phoFzZp1/KGuziBIXICsMbzv0Yf0/6yDg59YfkdGfbGKTqU4SYlwsoKa4dEWj14xjW4kGvwljI4rDETHbAbLIz20vWLCZaPDmHJxfokhOUH7TJIQHoSmMCF2IMs/IjwRmiKOb3kC0f+P6ERSmpaxwo0M3Ru1Fan10VXa+UnhlsygTJsPEA2/xa1Hbk8q0ZYJl/fBeh7ZFNmxH99MaBZUvARHsgQwGGMJDvsRcoV02L0rf8Z5k1K7fKqRTOh6GZ9gnmQz6fuFPMj8Vks2LcOruDpPJxRQujr0KxmueVE5EY9ePENYJSNOHSoEzTfe0QUM4vkHqPGtDC1Gcq9AosxCvDb7Nzypk4KOxYAIg024VPcBrAVzzjGRogvG16sSpAacHUbypoxDqoNFWv3awOXKHR4GopMQUvBsnDIcbBfcAgS2Jt/6sTkMBihNoKLfQVKufPo4QVdB4IC4MmUa2pcx8nPLlapuEhfp9Fgz/Y/vHw02ZFGjxv9wztVMx08Nl/SDwgkVNAczmCeNo5hP+RuO5/UeBRD13GM+Fv0w+TWN3hU=
  on:
    condition: "$FIREFOX_VERSION = latest"
    tags: true
repo: test-editor/test-editor-web

