version: "3"
services:
  persistence:
    image: testeditor/persistence:latest
    ports:
      - "9080:8080"
    environment:
      GIT_PRIVATE_KEY: "${GIT_PRIVATE_KEY}"
      KNOWN_HOSTS_CONTENT: "${KNOWN_HOSTS_CONTENT}"
      TARGET_REPO: "git@github.com:test-editor/language-examples.git"
      BRANCH_NAME: "feature/gonk"
      REPO_MODE: "pullPush"
  xtext:
    image: testeditor/xtext:latest
    ports:
      - "8080:8080"
    environment:
      GIT_PRIVATE_KEY: "${GIT_PRIVATE_KEY}"
      KNOWN_HOSTS_CONTENT: "${KNOWN_HOSTS_CONTENT}"
      TARGET_REPO: "git@github.com:test-editor/language-examples.git"
      BRANCH_NAME: "feature/gonk"
  web:
    image: testeditor/web:latest
    ports:
      - "4200:4200"
    depends_on:
      - persistence
      - xtext
