version: "3"
services:
  persistence:
    image: testeditor/persistence
    ports:
      - "9080:8080"
    environment:
      GIT_PRIVATE_KEY: "${GIT_PRIVATE_KEY}"
      KNOWN_HOSTS: "${KNOWN_HOSTS}"
      TARGET_REPO: "git@github.com:test-editor/language-examples.git"
      BRANCH_NAME: "feature/gonk"
      REPO_MODE: "pullPush"
  xtext:
    image: testeditor/xtext
    ports:
      - "8080:8080"
    environment:
      TARGET_REPO: "https://github.com/test-editor/language-examples.git"
      BRANCH_NAME: "feature/gonk"
  web:
    image: testeditor/web
    ports:
      - "4200:4200"
    depends_on:
      - persistence
      - xtext
