@startuml

title Test-Editor File Activity States
hide empty description

[*] --> Active
state Active {
  [*] -> Inactive

  state OpenIdle {
    state OpenedFile
    state OpenedDirtyFile
    state SelectedFile
    state SelectedDirtyFile
  }

  TypingIntoFile --> SelectedDirtyFile : stopTyping
  SelectedFile -> TypingIntoFile : typing
  Inactive --> OpenedFile : NAVIGATION_OPEN
  OpenIdle --> Inactive : close
  OpenedFile -> SelectedFile : EDITOR_ACTIVE
  SelectedFile -> OpenedFile : EDITOR_INACTIVE
  OpenedDirtyFile -right-> SelectedDirtyFile : EDITOR_ACTIVE
  SelectedDirtyFile -left-> OpenedDirtyFile : EDITOR_INACTIVE
  SelectedDirtyFile --> SelectedFile : save

  --
  [*] --> Persistence
  state Persistence {
    [*] -> ActionElapsed
    Persistence --> CreatedFile : create [in Inactive]
    Persistence --> SavedFile : save [in OpenedDirtyFile]
    Persistence --> DeletedFile : delete [!in TypingIntoFile]
    Persistence --> RenamedFile : rename [!in TypingIntoFile]
    CreatedFile --> ActionElapsed : after(5m)
    SavedFile --> ActionElapsed : after(5m)
    DeletedFile --> ActionElapsed : after(5m)
    RenamedFile --> ActionElapsed : after(5m)
  }
  --
  [*] -> TestExecutionIdle
  TestExecutionIdle -> TestExecutionRunning: start
  TestExecutionRunning -> TestExecutionIdle : terminate
}

@enduml
