@startuml

title
**Test-Editor Activity States**
//Overall user activity state, per workspace element and user.//
endtitle
hide empty description
skinparam Monochrome true

[*] --> Activity
state Activity {
  [*] -> Inactive

  state OpenIdle {
    state OpenedFile
    state OpenedDirtyFile
    state SelectedFile
    state SelectedDirtyFile
  }

  Inactive --> OpenedFile : NAVIGATION_OPEN
  OpenIdle --> Inactive : EDITOR_CLOSE
  OpenedFile --> SelectedFile : EDITOR_ACTIVE
  SelectedFile --> OpenedFile : EDITOR_INACTIVE
  OpenedDirtyFile --> SelectedDirtyFile : EDITOR_ACTIVE
  SelectedDirtyFile --> OpenedDirtyFile : EDITOR_INACTIVE
  SelectedDirtyFile --> SelectedFile : EDITOR_SAVE_COMPLETED
  SelectedDirtyFile --> SelectedFile : EDITOR_DIRTY_CHANGED [!dirty]
  SelectedFile --> SelectedDirtyFile : EDITOR_DIRTY_CHANGED [dirty]

  ' state TypingIntoFile as "<color: grey>TypingIntoFile"
  ' note bottom of TypingIntoFile : Not implemented
  ' TypingIntoFile -[#grey]-> SelectedDirtyFile : <color: grey>stopTyping
  ' SelectedFile -[#grey]> TypingIntoFile : <color: grey>typing

  --
  [*] -> CreatedFileElapsed
  CreatedFileElapsed -> CreatedFile : NAVIGATION_CREATED
  CreatedFile --> CreatedFile : NAVIGATION_CREATED
  CreatedFile -> CreatedFileElapsed : after(60s)
  --
  [*] -> SavedFileElapsed
  SavedFileElapsed -> SavedFile : EDITOR_SAVE_COMPLETED
  SavedFile --> SavedFile : EDITOR_SAVE_COMPLETED
  SavedFile -> SavedFileElapsed : after(60s)
  --
  [*] -> RenamedFileElapsed
  RenamedFileElapsed -> RenamedFile : NAVIGATION_RENAMED
  RenamedFile --> RenamedFile : NAVIGATION_RENAMED
  RenamedFile -> RenamedFileElapsed : after(60s)
  --
  [*] -> DeletedFileElapsed
  DeletedFileElapsed -> DeletedFile : NAVIGATION_DELETED
  DeletedFile --> DeletedFile : NAVIGATION_DELETED
  DeletedFile -> DeletedFileElapsed : after(60s)
  --
  [*] -> TestExecutionIdle
  TestExecutionIdle -> TestExecutionRunning: TEST_EXECUTION_STARTED
  TestExecutionRunning -> TestExecutionIdle : TEST_EXECUTION_FINISHED, TEST_EXECUTION_FAILED
}

@enduml
